//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: TestProto.proto
namespace MyGameProto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TestInfo")]
  public partial class TestInfo : global::ProtoBuf.IExtensible
  {
    public TestInfo() {}
    
    private int _userID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"userID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int userID
    {
      get { return _userID; }
      set { _userID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}